# Use official OpenJDK image from Docker Hub
FROM openjdk:17-jdk-slim

# Copy the compiled JAR file to the Docker container
COPY target/employee-management-system.jar app.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app.jar"]
